# Generated by Django 5.2.3 on 2025-06-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('supervisor', 'Supervisor'), ('empleado', 'Empleado')], max_length=20),
        ),
    ]
