# Generated by Django 5.2.3 on 2025-06-25 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('periodo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('dni_emp', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('dni_ent', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=255)),
                ('telefono1', models.CharField(max_length=20)),
                ('telefono2', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id_capacitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('entrenadores', models.ManyToManyField(related_name='capacitaciones', to='core.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id_esc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=100)),
                ('telefono1', models.CharField(blank=True, max_length=20)),
                ('telefono2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('documentos', models.ManyToManyField(related_name='escuelas', to='core.documento')),
            ],
        ),
        migrations.AddField(
            model_name='entrenador',
            name='escuela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrenadores', to='core.escuela'),
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('disciplina', models.CharField(max_length=100)),
                ('entrenadores', models.ManyToManyField(related_name='disciplinas', to='core.entrenador')),
                ('escuelas', models.ManyToManyField(related_name='disciplinas', to='core.escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('dni_alumno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=255)),
                ('fecha_nac', models.DateField()),
                ('disciplinas', models.ManyToManyField(related_name='alumnos', to='core.disciplina')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='core.escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('dni_reso', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono1', models.CharField(blank=True, max_length=20)),
                ('telefono2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='core.escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('dni_tutor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono1', models.CharField(max_length=20)),
                ('telefono2', models.CharField(max_length=20)),
                ('domicilio', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('alumnos', models.ManyToManyField(related_name='tutores', to='core.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('tipo', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='core.empleado')),
            ],
        ),
    ]
